In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\ARITRA\OneDrive - Manipal University Jaipur\Documents\data_sets\Anime.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21460 entries, 0 to 21459
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                21460 non-null  int64
 1   Title             21460 non-null  object
 2   Synonyms          21460 non-null  object
 3   Japanese          21460 non-null  object
 4   English           21460 non-null  object
 5   Synopsis          21460 non-null  object
 6   Type              21460 non-null  object
 7   Episodes          20913 non-null  float64
 8   Status            21460 non-null  object
 9   Start_Aired       21460 non-null  object
 10  End_Aired         21460 non-null  object
 11  Premiered         21460 non-null  object
 12  Broadcast         21460 non-null  object
 13  Producers         21460 non-null  object
 14  Licensors         21460 non-null  object
 15  Studios           21460 non-null  object
 16  Source            21460 non-null  object
 17  Genres            21460 non-null  object
 18  Themes            21460 non-null  object
 19  Demographics      21460 non-null  object
 20  Duration_Minutes  20861 non-null  float64
 21  Rating            20915 non-null  object
 22  Score             14562 non-null  float64
 23  Scored_Users      14562 non-null  float64
 24  Ranked            19536 non-null  float64
 25  Popularity        21460 non-null  int64
 26  Members           21460 non-null  int64
 27  Favorites         21460 non-null  int64
dtypes: float64(5), int64(4), object(19)
memory usage: 4.6+ MB

,ID,Title,Synonyms,Japanese,English,Synopsis,Type,Episodes,Status,Start_Aired,...,Themes,Demographics,Duration_Minutes,Rating,Score,Scored_Users,Ranked,Popularity,Members,Favorites
0,16498,Shingeki no Kyojin,"AoT, SnK",進撃の巨人,Attack on Titan,"Centuries ago, mankind was slaughtered to near...",TV,25.0,Finished Airing,"Apr 7, 2013",...,"Gore, Military, Survival",Shounen,24.0,R - 17+ (violence & profanity),8.531,519803.0,1002.0,1,3524109,155695
1,1535,Death Note,DN,デスノート,Death Note,"Brutal murders, petty thefts, and senseless vi...",TV,37.0,Finished Airing,"Oct 4, 2006",...,Psychological,Shounen,23.0,R - 17+ (violence & profanity),8.621,485487.0,732.0,2,3504535,159701
2,5114,Fullmetal Alchemist: Brotherhood,"Hagane no Renkinjutsushi Fullmetal Alchemist, ...",鋼の錬金術師 FULLMETAL ALCHEMIST,Fullmetal Alchemist Brotherhood,After a horrific alchemy experiment goes wrong...,TV,64.0,Finished Airing,"Apr 5, 2009",...,Military,Shounen,24.0,R - 17+ (violence & profanity),9.131,900398.0,12.0,3,2978455,207772
3,30276,One Punch Man,"One Punch-Man, One-Punch Man, OPM",ワンパンマン,One Punch Man,The seemingly unimpressive Saitama has a rathe...,TV,12.0,Finished Airing,"Oct 5, 2015",...,"Parody, Super Power",Seinen,24.0,R - 17+ (violence & profanity),8.511,19066.0,1112.0,4,2879907,59651
4,11757,Sword Art Online,"S.A.O, SAO",ソードアート・オンライン,Sword Art Online,Ever since the release of the innovative Nerve...,TV,25.0,Finished Airing,"Jul 8, 2012",...,"Love Polygon, Video Game",Unknown,23.0,PG-13 - Teens 13 or older,7.201,990254.0,29562.0,5,2813565,64997

In [3]:
df = df.drop(columns = ['Synonyms', 'Japanese', 'Type', 'Episodes', 'Producers', 'Premiered', 'Broadcast', 'Start_Aired', 'End_Aired', 'Licensors', 'Scored_Users', 'Members', 'Favorites', 'Popularity', 'Ranked', 'Duration_Minutes', 'Rating', 'Score'])

In [4]:
df.head(5)

,ID,Title,English,Synopsis,Status,Studios,Source,Genres,Themes,Demographics
0,16498,Shingeki no Kyojin,Attack on Titan,"Centuries ago, mankind was slaughtered to near...",Finished Airing,Wit Studio,Manga,"Action, Drama","Gore, Military, Survival",Shounen
1,1535,Death Note,Death Note,"Brutal murders, petty thefts, and senseless vi...",Finished Airing,Madhouse,Manga,"Supernatural, Suspense",Psychological,Shounen
2,5114,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist Brotherhood,After a horrific alchemy experiment goes wrong...,Finished Airing,Bones,Manga,"Action, Adventure, Drama, Fantasy",Military,Shounen
3,30276,One Punch Man,One Punch Man,The seemingly unimpressive Saitama has a rathe...,Finished Airing,Madhouse,Web manga,"Action, Comedy","Parody, Super Power",Seinen
4,11757,Sword Art Online,Sword Art Online,Ever since the release of the innovative Nerve...,Finished Airing,A-1 Pictures,Light novel,"Action, Adventure, Fantasy, Romance","Love Polygon, Video Game",Unknown

In [5]:
df.isnull().sum()

ID              0
Title           0
English         0
Synopsis        0
Status          0
Studios         0
Source          0
Genres          0
Themes          0
Demographics    0
dtype: int64

In [6]:
df = df.dropna()

In [7]:
df.isnull().sum()

ID              0
Title           0
English         0
Synopsis        0
Status          0
Studios         0
Source          0
Genres          0
Themes          0
Demographics    0
dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
df.head()

,ID,Title,English,Synopsis,Status,Studios,Source,Genres,Themes,Demographics
0,16498,Shingeki no Kyojin,Attack on Titan,"Centuries ago, mankind was slaughtered to near...",Finished Airing,Wit Studio,Manga,"Action, Drama","Gore, Military, Survival",Shounen
1,1535,Death Note,Death Note,"Brutal murders, petty thefts, and senseless vi...",Finished Airing,Madhouse,Manga,"Supernatural, Suspense",Psychological,Shounen
2,5114,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist Brotherhood,After a horrific alchemy experiment goes wrong...,Finished Airing,Bones,Manga,"Action, Adventure, Drama, Fantasy",Military,Shounen
3,30276,One Punch Man,One Punch Man,The seemingly unimpressive Saitama has a rathe...,Finished Airing,Madhouse,Web manga,"Action, Comedy","Parody, Super Power",Seinen
4,11757,Sword Art Online,Sword Art Online,Ever since the release of the innovative Nerve...,Finished Airing,A-1 Pictures,Light novel,"Action, Adventure, Fantasy, Romance","Love Polygon, Video Game",Unknown

In [10]:
data = {
  "Syn": []
}

df1 = pd.DataFrame(data)

df1['Syn'] = df['Synopsis']

df1.head(5)

df['Syn'] = df1
df.head(5)
# df.join(df1)
# pd.concat([df,df1])
# df.head(5)

,ID,Title,English,Synopsis,Status,Studios,Source,Genres,Themes,Demographics,Syn
0,16498,Shingeki no Kyojin,Attack on Titan,"Centuries ago, mankind was slaughtered to near...",Finished Airing,Wit Studio,Manga,"Action, Drama","Gore, Military, Survival",Shounen,"Centuries ago, mankind was slaughtered to near..."
1,1535,Death Note,Death Note,"Brutal murders, petty thefts, and senseless vi...",Finished Airing,Madhouse,Manga,"Supernatural, Suspense",Psychological,Shounen,"Brutal murders, petty thefts, and senseless vi..."
2,5114,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist Brotherhood,After a horrific alchemy experiment goes wrong...,Finished Airing,Bones,Manga,"Action, Adventure, Drama, Fantasy",Military,Shounen,After a horrific alchemy experiment goes wrong...
3,30276,One Punch Man,One Punch Man,The seemingly unimpressive Saitama has a rathe...,Finished Airing,Madhouse,Web manga,"Action, Comedy","Parody, Super Power",Seinen,The seemingly unimpressive Saitama has a rathe...
4,11757,Sword Art Online,Sword Art Online,Ever since the release of the innovative Nerve...,Finished Airing,A-1 Pictures,Light novel,"Action, Adventure, Fantasy, Romance","Love Polygon, Video Game",Unknown,Ever since the release of the innovative Nerve...

In [11]:
df['Synopsis'] = df['Synopsis'].apply(lambda x:x.split(' '))
df['English'] = df['English'].apply(lambda x:x.split(','))
df['Status'] = df['Status'].apply(lambda x:x.split(','))
df['Studios'] = df['Studios'].apply(lambda x:x.split(','))
df['Source'] = df['Source'].apply(lambda x:x.split(','))
df['Genres'] = df['Genres'].apply(lambda x:x.split(','))
df['Themes'] = df['Themes'].apply(lambda x:x.split(','))
df['Demographics'] = df['Demographics'].apply(lambda x:x.split())

In [12]:
df['English'] = df['English'].apply(lambda x:[i.replace(' ', '') for i in x])
df['Status'] = df['Status'].apply(lambda x:[i.replace(' ', '') for i in x])
df['Studios'] = df['Studios'].apply(lambda x:[i.replace(' ', '') for i in x])
df['Source'] = df['Source'].apply(lambda x:[i.replace(' ', '') for i in x])
df['Genres'] = df['Genres'].apply(lambda x:[i.replace(' ', '') for i in x])
df['Themes'] = df['Themes'].apply(lambda x:[i.replace(' ', '') for i in x])
df['Demographics'] = df['Demographics'].apply(lambda x:[i.replace(' ', '') for i in x])

In [13]:
df.head(5)

,ID,Title,English,Synopsis,Status,Studios,Source,Genres,Themes,Demographics,Syn
0,16498,Shingeki no Kyojin,[AttackonTitan],"[Centuries, ago,, mankind, was, slaughtered, t...",[FinishedAiring],[WitStudio],[Manga],"[Action, Drama]","[Gore, Military, Survival]",[Shounen],"Centuries ago, mankind was slaughtered to near..."
1,1535,Death Note,[DeathNote],"[Brutal, murders,, petty, thefts,, and, sensel...",[FinishedAiring],[Madhouse],[Manga],"[Supernatural, Suspense]",[Psychological],[Shounen],"Brutal murders, petty thefts, and senseless vi..."
2,5114,Fullmetal Alchemist: Brotherhood,[FullmetalAlchemistBrotherhood],"[After, a, horrific, alchemy, experiment, goes...",[FinishedAiring],[Bones],[Manga],"[Action, Adventure, Drama, Fantasy]",[Military],[Shounen],After a horrific alchemy experiment goes wrong...
3,30276,One Punch Man,[OnePunchMan],"[The, seemingly, unimpressive, Saitama, has, a...",[FinishedAiring],[Madhouse],[Webmanga],"[Action, Comedy]","[Parody, SuperPower]",[Seinen],The seemingly unimpressive Saitama has a rathe...
4,11757,Sword Art Online,[SwordArtOnline],"[Ever, since, the, release, of, the, innovativ...",[FinishedAiring],[A-1Pictures],[Lightnovel],"[Action, Adventure, Fantasy, Romance]","[LovePolygon, VideoGame]",[Unknown],Ever since the release of the innovative Nerve...

In [14]:
df['Tag'] = df['English'] + df['Synopsis'] + df['Status'] + df['Studios'] + df['Source'] + df['Genres'] + df['Themes'] + df['Demographics']

In [15]:
new_df = df[['ID', 'Title', 'Syn', 'Tag']]

In [16]:
new_df

,ID,Title,Syn,Tag
0,16498,Shingeki no Kyojin,"Centuries ago, mankind was slaughtered to near...","[AttackonTitan, Centuries, ago,, mankind, was,..."
1,1535,Death Note,"Brutal murders, petty thefts, and senseless vi...","[DeathNote, Brutal, murders,, petty, thefts,, ..."
2,5114,Fullmetal Alchemist: Brotherhood,After a horrific alchemy experiment goes wrong...,"[FullmetalAlchemistBrotherhood, After, a, horr..."
3,30276,One Punch Man,The seemingly unimpressive Saitama has a rathe...,"[OnePunchMan, The, seemingly, unimpressive, Sa..."
4,11757,Sword Art Online,Ever since the release of the innovative Nerve...,"[SwordArtOnline, Ever, since, the, release, of..."
...,...,...,...,...
21455,45064,Xiao Gongzhu Ai Wei La Yu Shenmi Wangguo,Unknown,"[PrincessandtheKingdom, Unknown, FinishedAirin..."
21456,45065,Xiao Gongzhu Ai Wei La Yu Shenmi Wangguo 2,Unknown,"[AveraandtheMysticalKingdom2, Unknown, Finishe..."
21457,45059,Yongzhe Chuang Mo Cheng,Unknown,"[BraveCity, Unknown, FinishedAiring, Unknown, ..."
21458,45063,Yu Shen Chuan: Wangzhe Shaonian,Unknown,"[TheJuvenileofKingYu, Unknown, FinishedAiring,..."
21459,45061,Konglong Wang,Unknown,"[DinoKing, Unknown, FinishedAiring, Unknown, O..."

In [17]:
new_df['Tag'] = new_df['Tag'].apply(lambda x:" ".join(x))

C:\Users\ARITRA\AppData\Local\Temp\ipykernel_25872\767450711.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Tag'] = new_df['Tag'].apply(lambda x:" ".join(x))

In [18]:
new_df.head(5)

,ID,Title,Syn,Tag
0,16498,Shingeki no Kyojin,"Centuries ago, mankind was slaughtered to near...","AttackonTitan Centuries ago, mankind was slaug..."
1,1535,Death Note,"Brutal murders, petty thefts, and senseless vi...","DeathNote Brutal murders, petty thefts, and se..."
2,5114,Fullmetal Alchemist: Brotherhood,After a horrific alchemy experiment goes wrong...,FullmetalAlchemistBrotherhood After a horrific...
3,30276,One Punch Man,The seemingly unimpressive Saitama has a rathe...,OnePunchMan The seemingly unimpressive Saitama...
4,11757,Sword Art Online,Ever since the release of the innovative Nerve...,SwordArtOnline Ever since the release of the i...

In [19]:
new_df['Tag'][0]

'AttackonTitan Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called Titans, forcing humans to hide in fear behind enormous concentric walls. What makes these giants truly terrifying is that their taste for human flesh is not born out of hunger but what appears to be out of pleasure. To ensure their survival, the remnants of humanity began living within defensive barriers, resulting in one hundred years without a single titan encounter. However, that fragile calm is soon shattered when a colossal Titan manages to breach the supposedly impregnable outer wall, reigniting the fight for survival against the man-eating abominations.\n\r\nAfter witnessing a horrific personal loss at the hands of the invading creatures, Eren Yeager dedicates his life to their eradication by enlisting into the Survey Corps, an elite military unit that combats the merciless humanoids outside the protection of the walls. Eren, his adopted sister Mikasa Ackerman, and his childhood friend Armin Arlert join the brutal war against the Titans and race to discover a way of defeating them before the last walls are breached.\n\r\n[Written by MAL Rewrite] FinishedAiring WitStudio Manga Action Drama Gore Military Survival Shounen'

In [20]:
new_df['Tag'][1]

'DeathNote Brutal murders, petty thefts, and senseless violence pollute the human world. In contrast, the realm of death gods is a humdrum, unchanging gambling den. The ingenious 17-year-old Japanese student Light Yagami and sadistic god of death Ryuk share one belief: their worlds are rotten.\n\r\nFor his own amusement, Ryuk drops his "Death Note" into the human world. Light stumbles upon it, deeming the first of its rules ridiculous: the human whose name is written in this note shall die. However, the temptation is too great, and Light experiments by writing a felon\'s name, which disturbingly enacts his first murder.\n\r\nAware of the terrifying godlike power that has fallen into his hands, Light—under the alias "Kira"—follows his wicked sense of justice with the ultimate goal of cleansing the world of all evil-doers. The meticulous mastermind detective L is already on his trail, but as Light\'s brilliance rivals L\'s, the grand chase for Kira turns into an intense battle of wits that can only end when one of them is dead.\n\r\n[Written by MAL Rewrite]\n FinishedAiring Madhouse Manga Supernatural Suspense Psychological Shounen'

In [21]:
new_df['Tag'] = new_df['Tag'].apply(lambda x:x.lower())

C:\Users\ARITRA\AppData\Local\Temp\ipykernel_25872\988575235.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Tag'] = new_df['Tag'].apply(lambda x:x.lower())

In [22]:
new_df.head(5)

,ID,Title,Syn,Tag
0,16498,Shingeki no Kyojin,"Centuries ago, mankind was slaughtered to near...","attackontitan centuries ago, mankind was slaug..."
1,1535,Death Note,"Brutal murders, petty thefts, and senseless vi...","deathnote brutal murders, petty thefts, and se..."
2,5114,Fullmetal Alchemist: Brotherhood,After a horrific alchemy experiment goes wrong...,fullmetalalchemistbrotherhood after a horrific...
3,30276,One Punch Man,The seemingly unimpressive Saitama has a rathe...,onepunchman the seemingly unimpressive saitama...
4,11757,Sword Art Online,Ever since the release of the innovative Nerve...,swordartonline ever since the release of the i...

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [24]:
vector = cv.fit_transform(new_df['Tag']).toarray()

In [25]:
vector.shape

(21460, 5000)

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

In [27]:
similarity = cosine_similarity(vector)

In [28]:
similarity

array([[1.        , 0.11026853, 0.14978119, ..., 0.02052821, 0.02103516,
        0.03135736],
       [0.11026853, 1.        , 0.12667365, ..., 0.01967604, 0.02016195,
        0.03005565],
       [0.14978119, 0.12667365, 1.        , ..., 0.06131393, 0.06282809,
        0.06243905],
       ...,
       [0.02052821, 0.01967604, 0.06131393, ..., 1.        , 0.97590007,
        0.80013226],
       [0.02103516, 0.02016195, 0.06282809, ..., 0.97590007, 1.        ,
        0.81989159],
       [0.03135736, 0.03005565, 0.06243905, ..., 0.80013226, 0.81989159,
        1.        ]])

In [29]:
def recommend(anime):
    index = new_df[new_df['Title'] == anime].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_df.iloc[i[0]].Title)

In [30]:
recommend('86')

86 Part 2
86 Special Edition: Senya ni Akaku Hinageshi no Saku
86 Part 2 Recaps
Soukou Kihei Votoms Vol.II: Highlights from the "A.T.Votoms"
Senjou no Valkyria 3: Tagatame no Juusou

In [31]:
import pickle

In [32]:
pickle.dump(new_df.to_dict(),open('anime_dict.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))